"""replace is_active with bio

Revision ID: b35dd8597c80
Revises: c9cc241fa2c5
Create Date: 2026-03-16 16:53:27.324646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35dd8597c80'
down_revision: Union[str, None] = 'c9cc241fa2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
